package com.example.udyongbayanihan;
import java.util.HashMap;
import java.util.Map;
public class BarangayDistances {
    private static final Map<String, Map<String, Integer>> distances = new HashMap<>();

    static {
        Map<String, Integer> arellanoDistances = new HashMap<>();
        arellanoDistances.put("Arellano", 0);
        arellanoDistances.put("Bagumbayan", 210);
        arellanoDistances.put("Balagtas", 900);
        arellanoDistances.put("Balut", 600);
        arellanoDistances.put("Bantan", 4000);
        arellanoDistances.put("Bilolo", 2200);
        arellanoDistances.put("Calungusan", 2600);
        arellanoDistances.put("Camachile", 3200);
        arellanoDistances.put("Daang Bago", 1400);
        arellanoDistances.put("Daang Bilolo", 1200);
        arellanoDistances.put("Daang Pare", 2900);
        arellanoDistances.put("General Lim", 3800);
        arellanoDistances.put("Kapunitan", 1300);
        arellanoDistances.put("Lati", 750);
        arellanoDistances.put("Lusungan", 950);
        arellanoDistances.put("Puting Buhangin", 4700);
        arellanoDistances.put("Sabatan", 4100);
        arellanoDistances.put("San Vicente", 1800);
        arellanoDistances.put("Santa Elena", 5100);
        arellanoDistances.put("Santo Domingo", 2800);
        arellanoDistances.put("Villa Angeles", 650);
        arellanoDistances.put("Wakas", 2600);
        arellanoDistances.put("Wawa",1300);
        distances.put("Arellano", arellanoDistances);

        Map<String, Integer> bagumbayanDistances = new HashMap<>();
        bagumbayanDistances.put("Bagumbayan", 0);
        bagumbayanDistances.put("Arellano", 210);
        bagumbayanDistances.put("Balagtas", 1100);
        bagumbayanDistances.put("Balut", 550);
        bagumbayanDistances.put("Bantan", 4200);
        bagumbayanDistances.put("Bilolo", 1800);
        bagumbayanDistances.put("Calungusan", 2800);
        bagumbayanDistances.put("Camachile", 3500);
        bagumbayanDistances.put("Daang Bago", 1300);
        bagumbayanDistances.put("Daang Bilolo", 1200);
        bagumbayanDistances.put("Daang Pare", 2800);
        bagumbayanDistances.put("General Lim", 3800);
        bagumbayanDistances.put("Kapunitan", 1200);
        bagumbayanDistances.put("Lati", 650);
        bagumbayanDistances.put("Lusungan", 900);
        bagumbayanDistances.put("Puting Buhangin", 4700);
        bagumbayanDistances.put("Sabatan", 4100);
        bagumbayanDistances.put("San Vicente", 2000);
        bagumbayanDistances.put("Santa Elena", 5100);
        bagumbayanDistances.put("Santo Domingo", 3000);
        bagumbayanDistances.put("Villa Angeles", 600);
        bagumbayanDistances.put("Wakas", 2600);
        bagumbayanDistances.put("Wawa", 1200);
        distances.put("Bagumbayan", bagumbayanDistances);

        Map<String, Integer> balagtasDistances = new HashMap<>();
        balagtasDistances.put("Balagtas", 0);
        balagtasDistances.put("Arellano", 900);
        balagtasDistances.put("Bagumbayan", 1100);
        balagtasDistances.put("Balut", 1500);
        balagtasDistances.put("Bantan", 3000);
        balagtasDistances.put("Bilolo", 2500);
        balagtasDistances.put("Calungusan", 1700);
        balagtasDistances.put("Camachile", 2300);
        balagtasDistances.put("Daang Bago", 2300);
        balagtasDistances.put("Daang Bilolo", 1900);
        balagtasDistances.put("Daang Pare", 3600);
        balagtasDistances.put("General Lim", 4600);
        balagtasDistances.put("Kapunitan", 2200);
        balagtasDistances.put("Lati", 1600);
        balagtasDistances.put("Lusungan", 1900);
        balagtasDistances.put("Puting Buhangin", 5500);
        balagtasDistances.put("Sabatan", 4800);
        balagtasDistances.put("San Vicente", 2500);
        balagtasDistances.put("Santa Elena", 5800);
        balagtasDistances.put("Santo Domingo", 1900);
        balagtasDistances.put("Villa Angeles", 1600);
        balagtasDistances.put("Wakas", 3400);
        balagtasDistances.put("Wawa", 2200);
        distances.put("Balagtas", balagtasDistances);

        Map<String, Integer> balutDistances = new HashMap<>();
        balutDistances.put("Balut", 0);
        balutDistances.put("Arellano", 600);
        balutDistances.put("Bagumbayan", 550);
        balutDistances.put("Balagtas", 1500);
        balutDistances.put("Bantan", 4600);
        balutDistances.put("Bilolo", 2300);
        balutDistances.put("Calungusan", 3200);
        balutDistances.put("Camachile", 3900);
        balutDistances.put("Daang Bago", 1900);
        balutDistances.put("Daang Bilolo", 1700);
        balutDistances.put("Daang Pare", 3300);
        balutDistances.put("General Lim", 4300);
        balutDistances.put("Kapunitan", 1700);
        balutDistances.put("Lati", 1200);
        balutDistances.put("Lusungan", 1400);
        balutDistances.put("Puting Buhangin", 5200);
        balutDistances.put("Sabatan", 4600);
        balutDistances.put("San Vicente", 2400);
        balutDistances.put("Santa Elena", 5600);
        balutDistances.put("Santo Domingo", 3400);
        balutDistances.put("Villa Angeles", 1100);
        balutDistances.put("Wakas", 3100);
        balutDistances.put("Wawa", 1700);
        distances.put("Balut", balutDistances);

        Map<String, Integer> bantanDistances = new HashMap<>();
        bantanDistances.put("Bantan", 0);
        bantanDistances.put("Arellano", 4000);
        bantanDistances.put("Bagumbayan", 4200);
        bantanDistances.put("Balagtas", 3000);
        bantanDistances.put("Balut", 4600);
        bantanDistances.put("Bilolo", 7300);
        bantanDistances.put("Calungusan", 1400);
        bantanDistances.put("Camachile", 2400);
        bantanDistances.put("Daang Bago", 5400);
        bantanDistances.put("Daang Bilolo", 4900);
        bantanDistances.put("Daang Pare", 6600);
        bantanDistances.put("General Lim", 9000);
        bantanDistances.put("Kapunitan", 5400);
        bantanDistances.put("Lati", 4700);
        bantanDistances.put("Lusungan", 5000);
        bantanDistances.put("Puting Buhangin", 11700);
        bantanDistances.put("Sabatan", 9400);
        bantanDistances.put("San Vicente", 5600);
        bantanDistances.put("Santa Elena", 12000);
        bantanDistances.put("Santo Domingo", 3500);
        bantanDistances.put("Villa Angeles", 4600);
        bantanDistances.put("Wakas", 8600);
        bantanDistances.put("Wawa", 5200);
        distances.put("Bantan", bantanDistances);

        Map<String, Integer> biloloDistances = new HashMap<>();
        biloloDistances.put("Bilolo", 0);
        biloloDistances.put("Arellano", 1800);
        biloloDistances.put("Bagumbayan", 1900);
        biloloDistances.put("Balagtas", 2500);
        biloloDistances.put("Balut", 2400);
        biloloDistances.put("Bantan", 7300);
        biloloDistances.put("Calungusan", 6000);
        biloloDistances.put("Camachile", 6600);
        biloloDistances.put("Daang Bago", 2700);
        biloloDistances.put("Daang Bilolo", 1100);
        biloloDistances.put("Daang Pare", 2600);
        biloloDistances.put("General Lim", 2000);
        biloloDistances.put("Kapunitan", 2500);
        biloloDistances.put("Lati", 2000);
        biloloDistances.put("Lusungan", 2200);
        biloloDistances.put("Puting Buhangin", 4600);
        biloloDistances.put("Sabatan", 2300);
        biloloDistances.put("San Vicente", 3200);
        biloloDistances.put("Santa Elena", 4900);
        biloloDistances.put("Santo Domingo", 4300);
        biloloDistances.put("Villa Angeles", 1900);
        biloloDistances.put("Wakas",1500);
        biloloDistances.put("Wawa", 2500);
        distances.put("Bilolo", biloloDistances);

        Map<String, Integer> calungusanDistances = new HashMap<>();
        calungusanDistances.put("Calungusan", 0);
        calungusanDistances.put("Arellano", 2600);
        calungusanDistances.put("Bagumbayan", 2800);
        calungusanDistances.put("Balagtas", 1700);
        calungusanDistances.put("Balut", 3200);
        calungusanDistances.put("Bantan", 1400);
        calungusanDistances.put("Bilolo", 6000);
        calungusanDistances.put("Camachile", 1100);
        calungusanDistances.put("Daang Bago", 4000);
        calungusanDistances.put("Daang Bilolo", 3600);
        calungusanDistances.put("Daang Pare", 8400);
        calungusanDistances.put("General Lim", 7700);
        calungusanDistances.put("Kapunitan", 3800);
        calungusanDistances.put("Lati", 3300);
        calungusanDistances.put("Lusungan", 3600);
        calungusanDistances.put("Puting Buhangin", 10400);
        calungusanDistances.put("Sabatan", 8100);
        calungusanDistances.put("San Vicente", 4200);
        calungusanDistances.put("Santa Elena", 10700);
        calungusanDistances.put("Santo Domingo", 2200);
        calungusanDistances.put("Villa Angeles", 3300);
        calungusanDistances.put("Wakas", 7300);
        calungusanDistances.put("Wawa", 3900);
        distances.put("Calungusan", calungusanDistances);

        Map<String, Integer> camachileDistances = new HashMap<>();
        camachileDistances.put("Camachile", 0);
        camachileDistances.put("Arellano", 3200);
        camachileDistances.put("Bagumbayan", 3500);
        camachileDistances.put("Balagtas", 2300);
        camachileDistances.put("Balut", 3900);
        camachileDistances.put("Bantan", 2400);
        camachileDistances.put("Bilolo", 6600);
        camachileDistances.put("Calungusan", 1100);
        camachileDistances.put("Daang Bago", 4700);
        camachileDistances.put("Daang Bilolo", 4200);
        camachileDistances.put("Daang Pare", 9100);
        camachileDistances.put("General Lim", 8300);
        camachileDistances.put("Kapunitan", 4500);
        camachileDistances.put("Lati", 4000);
        camachileDistances.put("Lusungan", 4300);
        camachileDistances.put("Puting Buhangin", 11000);
        camachileDistances.put("Sabatan", 8700);
        camachileDistances.put("San Vicente", 4900);
        camachileDistances.put("Santa Elena", 11300);
        camachileDistances.put("Santo Domingo", 2800);
        camachileDistances.put("Villa Angeles", 3900);
        camachileDistances.put("Wakas", 7900);
        camachileDistances.put("Wawa", 4500);
        distances.put("Camachile", camachileDistances);

        Map<String, Integer> daangbagoDistances = new HashMap<>();
        daangbagoDistances.put("Daang Bago", 0);
        daangbagoDistances.put("Arellano", 1400);
        daangbagoDistances.put("Bagumbayan", 1300);
        daangbagoDistances.put("Balagtas", 2300);
        daangbagoDistances.put("Balut", 1900);
        daangbagoDistances.put("Bantan", 5400);
        daangbagoDistances.put("Bilolo", 2700);
        daangbagoDistances.put("Calungusan", 4000);
        daangbagoDistances.put("Camachile", 4700);
        daangbagoDistances.put("Daang Bilolo", 2100);
        daangbagoDistances.put("Daang Pare", 3700);
        daangbagoDistances.put("General Lim", 4700);
        daangbagoDistances.put("Kapunitan", 1400);
        daangbagoDistances.put("Lati", 1300);
        daangbagoDistances.put("Lusungan", 900);
        daangbagoDistances.put("Puting Buhangin", 5600);
        daangbagoDistances.put("Sabatan", 5000);
        daangbagoDistances.put("San Vicente", 3000);
        daangbagoDistances.put("Santa Elena", 6000);
        daangbagoDistances.put("Santo Domingo", 4200);
        daangbagoDistances.put("Villa Angeles", 1300);
        daangbagoDistances.put("Wakas", 3500);
        daangbagoDistances.put("Wawa", 140);
        distances.put("Daang Bago", daangbagoDistances);

        Map<String, Integer> daangbiloloDistances = new HashMap<>();
        daangbiloloDistances.put("Daang Bilolo", 0);
        daangbiloloDistances.put("Arellano", 1200);
        daangbiloloDistances.put("Bagumbayan", 1300);
        daangbiloloDistances.put("Balagtas", 1900);
        daangbiloloDistances.put("Balut", 1800);
        daangbiloloDistances.put("Bantan", 4900);
        daangbiloloDistances.put("Bilolo", 1100);
        daangbiloloDistances.put("Calungusan", 3600);
        daangbiloloDistances.put("Camachile", 4200);
        daangbiloloDistances.put("Daang Bago", 2100);
        daangbiloloDistances.put("Daang Pare", 3700);
        daangbiloloDistances.put("General Lim", 3100);
        daangbiloloDistances.put("Kapunitan", 1900);
        daangbiloloDistances.put("Lati", 1400);
        daangbiloloDistances.put("Lusungan", 1600);
        daangbiloloDistances.put("Puting Buhangin", 5700);
        daangbiloloDistances.put("Sabatan", 3400);
        daangbiloloDistances.put("San Vicente", 2600);
        daangbiloloDistances.put("Santa Elena", 6000);
        daangbiloloDistances.put("Santo Domingo", 5400);
        daangbiloloDistances.put("Villa Angeles", 1300);
        daangbiloloDistances.put("Wakas", 1900);
        daangbiloloDistances.put("Wawa", 1900);
        distances.put("Daang Bilolo", daangbiloloDistances);

        Map<String, Integer> daangpareDistances = new HashMap<>();
        daangpareDistances.put("Daang Pare", 0);
        daangpareDistances.put("Arellano", 3200);
        daangpareDistances.put("Bagumbayan", 3100);
        daangpareDistances.put("Balagtas", 4000);
        daangpareDistances.put("Balut", 3700);
        daangpareDistances.put("Bantan", 9800);
        daangpareDistances.put("Bilolo", 2600);
        daangpareDistances.put("Calungusan", 8400);
        daangpareDistances.put("Camachile", 9100);
        daangpareDistances.put("Daang Bago", 4100);
        daangpareDistances.put("Daang Bilolo", 3700);
        daangpareDistances.put("General Lim", 4500);
        daangpareDistances.put("Kapunitan", 3300);
        daangpareDistances.put("Lati", 3100);
        daangpareDistances.put("Lusungan", 3400);
        daangpareDistances.put("Puting Buhangin", 2700);
        daangpareDistances.put("Sabatan", 4000);
        daangpareDistances.put("San Vicente", 4700);
        daangpareDistances.put("Santa Elena", 2300);
        daangpareDistances.put("Santo Domingo", 6700);
        daangpareDistances.put("Villa Angeles", 2700);
        daangpareDistances.put("Wakas", 2300);
        daangpareDistances.put("Wawa", 3900);
        distances.put("Daang Pare", daangpareDistances);

        Map<String, Integer> generallimDistances = new HashMap<>();
        generallimDistances.put("General Lim", 0);
        generallimDistances.put("Arellano", 3800);
        generallimDistances.put("Bagumbayan", 3900);
        generallimDistances.put("Balagtas", 4600);
        generallimDistances.put("Balut", 4400);
        generallimDistances.put("Bantan", 9200);
        generallimDistances.put("Bilolo", 2000);
        generallimDistances.put("Calungusan", 7800);
        generallimDistances.put("Camachile", 8500);
        generallimDistances.put("Daang Bago", 4700);
        generallimDistances.put("Daang Bilolo", 3100);
        generallimDistances.put("Daang Pare", 4500);
        generallimDistances.put("Kapunitan", 4500);
        generallimDistances.put("Lati", 4000);
        generallimDistances.put("Lusungan", 4300);
        generallimDistances.put("Puting Buhangin", 6400);
        generallimDistances.put("Sabatan", 4100);
        generallimDistances.put("San Vicente", 5300);
        generallimDistances.put("Santa Elena", 6700);
        generallimDistances.put("Santo Domingo", 6100);
        generallimDistances.put("Villa Angeles", 3900);
        generallimDistances.put("Wakas", 3300);
        generallimDistances.put("Wawa", 4600);
        distances.put("General Lim", generallimDistances);

        Map<String, Integer> kapunitanDistances = new HashMap<>();
        kapunitanDistances.put("Kapunitan", 0);
        kapunitanDistances.put("Arellano", 1300);
        kapunitanDistances.put("Bagumbayan", 1200);
        kapunitanDistances.put("Balagtas", 2200);
        kapunitanDistances.put("Balut", 1700);
        kapunitanDistances.put("Bantan", 5200);
        kapunitanDistances.put("Bilolo", 2500);
        kapunitanDistances.put("Calungusan", 3900);
        kapunitanDistances.put("Camachile", 4500);
        kapunitanDistances.put("Daang Bago", 1400);
        kapunitanDistances.put("Daang Bilolo", 1900);
        kapunitanDistances.put("Daang Pare", 3200);
        kapunitanDistances.put("General Lim", 4500);
        kapunitanDistances.put("Lati", 800);
        kapunitanDistances.put("Lusungan", 500);
        kapunitanDistances.put("Puting Buhangin", 5100);
        kapunitanDistances.put("Sabatan", 4800);
        kapunitanDistances.put("San Vicente", 2900);
        kapunitanDistances.put("Santa Elena", 5500);
        kapunitanDistances.put("Santo Domingo", 4000);
        kapunitanDistances.put("Villa Angeles", 500);
        kapunitanDistances.put("Wakas", 4800);
        kapunitanDistances.put("Wawa", 1300);
        distances.put("Kapunitan", kapunitanDistances);

        Map<String, Integer> latiDistances = new HashMap<>();
        latiDistances.put("Lati", 0);
        latiDistances.put("Arellano", 750);
        latiDistances.put("Bagumbayan", 650);
        latiDistances.put("Balagtas", 1700);
        latiDistances.put("Balut", 1200);
        latiDistances.put("Bantan", 4700);
        latiDistances.put("Bilolo", 2000);
        latiDistances.put("Calungusan", 3400);
        latiDistances.put("Camachile", 4000);
        latiDistances.put("Daang Bago", 1300);
        latiDistances.put("Daang Bilolo", 1400);
        latiDistances.put("Daang Pare", 2700);
        latiDistances.put("General Lim", 4000);
        latiDistances.put("Kapunitan", 800);
        latiDistances.put("Lusungan", 600);
        latiDistances.put("Puting Buhangin", 4600);
        latiDistances.put("Sabatan", 4300);
        latiDistances.put("San Vicente", 2300);
        latiDistances.put("Santa Elena", 5000);
        latiDistances.put("Santo Domingo", 3500);
        latiDistances.put("Villa Angeles", 300);
        latiDistances.put("Wakas", 4300);
        latiDistances.put("Wawa", 1200);
        distances.put("Lati", latiDistances);

        Map<String, Integer> lusunganDistances = new HashMap<>();
        lusunganDistances.put("Lusungan", 0);
        lusunganDistances.put("Arellano", 1000);
        lusunganDistances.put("Bagumbayan", 900);
        lusunganDistances.put("Balagtas", 1900);
        lusunganDistances.put("Balut", 1400);
        lusunganDistances.put("Bantan", 5000);
        lusunganDistances.put("Bilolo", 2200);
        lusunganDistances.put("Calungusan", 3600);
        lusunganDistances.put("Camachile", 4300);
        lusunganDistances.put("Daang Bago", 900);
        lusunganDistances.put("Daang Bilolo", 1600);
        lusunganDistances.put("Daang Pare", 3000);
        lusunganDistances.put("General Lim", 4300);
        lusunganDistances.put("Kapunitan", 500);
        lusunganDistances.put("Lati", 600);
        lusunganDistances.put("Puting Buhangin", 4900);
        lusunganDistances.put("Sabatan", 4600);
        lusunganDistances.put("San Vicente", 2700);
        lusunganDistances.put("Santa Elena", 5300);
        lusunganDistances.put("Santo Domingo", 3800);
        lusunganDistances.put("Villa Angeles", 600);
        lusunganDistances.put("Wakas", 4600);
        lusunganDistances.put("Wawa", 750);
        distances.put("Lusungan", lusunganDistances);

        Map<String, Integer> putingbuhanginDistances = new HashMap<>();
        putingbuhanginDistances.put("Puting Buhangin", 0);
        putingbuhanginDistances.put("Arellano", 4700);
        putingbuhanginDistances.put("Bagumbayan", 4600);
        putingbuhanginDistances.put("Balagtas", 5500);
        putingbuhanginDistances.put("Balut", 5300);
        putingbuhanginDistances.put("Bantan", 11700);
        putingbuhanginDistances.put("Bilolo", 4600);
        putingbuhanginDistances.put("Calungusan", 10400);
        putingbuhanginDistances.put("Camachile", 11000);
        putingbuhanginDistances.put("Daang Bago", 5600);
        putingbuhanginDistances.put("Daang Bilolo", 5700);
        putingbuhanginDistances.put("Daang Pare", 2700);
        putingbuhanginDistances.put("General Lim", 6400);
        putingbuhanginDistances.put("Kapunitan", 4800);
        putingbuhanginDistances.put("Lati", 4600);
        putingbuhanginDistances.put("Lusungan", 4900);
        putingbuhanginDistances.put("Sabatan", 5900);
        putingbuhanginDistances.put("San Vicente", 6200);
        putingbuhanginDistances.put("Santa Elena", 4900);
        putingbuhanginDistances.put("Santo Domingo", 8700);
        putingbuhanginDistances.put("Villa Angeles", 4300);
        putingbuhanginDistances.put("Wakas", 4300);
        putingbuhanginDistances.put("Wawa", 5400);
        distances.put("Puting Buhangin", putingbuhanginDistances);

        Map<String, Integer> sabatanDistances = new HashMap<>();
        sabatanDistances.put("Sabatan", 0);
        sabatanDistances.put("Arellano", 3800);
        sabatanDistances.put("Bagumbayan", 3900);
        sabatanDistances.put("Balagtas", 4500);
        sabatanDistances.put("Balut", 4400);
        sabatanDistances.put("Bantan", 9400);
        sabatanDistances.put("Bilolo", 2300);
        sabatanDistances.put("Calungusan", 8100);
        sabatanDistances.put("Camachile", 8700);
        sabatanDistances.put("Daang Bago", 4700);
        sabatanDistances.put("Daang Bilolo", 3100);
        sabatanDistances.put("Daang Pare", 4000);
        sabatanDistances.put("General Lim", 4100);
        sabatanDistances.put("Kapunitan", 4500);
        sabatanDistances.put("Lati", 4000);
        sabatanDistances.put("Lusungan", 4300);
        sabatanDistances.put("Puting Buhangin", 5900);
        sabatanDistances.put("San Vicente", 5200);
        sabatanDistances.put("Santa Elena", 6200);
        sabatanDistances.put("Santo Domingo", 6400);
        sabatanDistances.put("Villa Angeles", 4800);
        sabatanDistances.put("Wakas", 3300);
        sabatanDistances.put("Wawa", 4500);
        distances.put("Sabatan", sabatanDistances);

        Map<String, Integer> sanvicenteDistances = new HashMap<>();
        sanvicenteDistances.put("San Vicente", 0);
        sanvicenteDistances.put("Arellano", 1800);
        sanvicenteDistances.put("Bagumbayan", 1900);
        sanvicenteDistances.put("Balagtas", 2500);
        sanvicenteDistances.put("Balut", 2400);
        sanvicenteDistances.put("Bantan", 5600);
        sanvicenteDistances.put("Bilolo", 3200);
        sanvicenteDistances.put("Calungusan", 4200);
        sanvicenteDistances.put("Camachile", 4900);
        sanvicenteDistances.put("Daang Bago", 3000);
        sanvicenteDistances.put("Daang Bilolo", 2600);
        sanvicenteDistances.put("Daang Pare", 4300);
        sanvicenteDistances.put("General Lim", 5300);
        sanvicenteDistances.put("Kapunitan", 2900);
        sanvicenteDistances.put("Lati", 2300);
        sanvicenteDistances.put("Lusungan", 2700);
        sanvicenteDistances.put("Puting Buhangin", 6200);
        sanvicenteDistances.put("Sabatan", 5500);
        sanvicenteDistances.put("Santa Elena", 6500);
        sanvicenteDistances.put("Santo Domingo", 4400);
        sanvicenteDistances.put("Villa Angeles", 2300);
        sanvicenteDistances.put("Wakas", 4100);
        sanvicenteDistances.put("Wawa", 2900);
        distances.put("San Vicente", sanvicenteDistances);

        Map<String, Integer> santaelenaDistances = new HashMap<>();
        santaelenaDistances.put("Santa Elena", 0);
        santaelenaDistances.put("Arellano", 5500);
        santaelenaDistances.put("Bagumbayan", 5400);
        santaelenaDistances.put("Balagtas", 6200);
        santaelenaDistances.put("Balut", 5900);
        santaelenaDistances.put("Bantan", 12000);
        santaelenaDistances.put("Bilolo", 4900);
        santaelenaDistances.put("Calungusan", 10700);
        santaelenaDistances.put("Camachile", 11300);
        santaelenaDistances.put("Daang Bago", 6300);
        santaelenaDistances.put("Daang Bilolo", 6000);
        santaelenaDistances.put("Daang Pare", 2300);
        santaelenaDistances.put("General Lim", 6700);
        santaelenaDistances.put("Kapunitan", 5500);
        santaelenaDistances.put("Lati", 5400);
        santaelenaDistances.put("Lusungan", 5700);
        santaelenaDistances.put("Puting Buhangin", 4900);
        santaelenaDistances.put("Sabatan", 6200);
        santaelenaDistances.put("San Vicente", 6900);
        santaelenaDistances.put("Santo Domingo", 9000);
        santaelenaDistances.put("Villa Angeles", 5000);
        santaelenaDistances.put("Wakas", 4600);
        santaelenaDistances.put("Wawa", 6200);
        distances.put("Santa Elena", santaelenaDistances);

        Map<String, Integer> santodomingoDistances = new HashMap<>();
        santodomingoDistances.put("Santo Domingo", 0);
        santodomingoDistances.put("Arellano", 2800);
        santodomingoDistances.put("Bagumbayan", 3000);
        santodomingoDistances.put("Balagtas", 1900);
        santodomingoDistances.put("Balut", 3400);
        santodomingoDistances.put("Bantan", 3500);
        santodomingoDistances.put("Bilolo", 4300);
        santodomingoDistances.put("Calungusan", 2200);
        santodomingoDistances.put("Camachile", 2800);
        santodomingoDistances.put("Daang Bago", 4200);
        santodomingoDistances.put("Daang Bilolo", 5400);
        santodomingoDistances.put("Daang Pare", 6700);
        santodomingoDistances.put("General Lim", 6000);
        santodomingoDistances.put("Kapunitan", 4000);
        santodomingoDistances.put("Lati", 3500);
        santodomingoDistances.put("Lusungan", 3800);
        santodomingoDistances.put("Puting Buhangin", 8700);
        santodomingoDistances.put("Sabatan", 6400);
        santodomingoDistances.put("San Vicente", 4400);
        santodomingoDistances.put("Santa Elena", 9000);
        santodomingoDistances.put("Villa Angeles", 3400);
        santodomingoDistances.put("Wakas", 5600);
        santodomingoDistances.put("Wawa", 4100);
        distances.put("Santo Domingo", santodomingoDistances);

        Map<String, Integer> villaangelesDistances = new HashMap<>();
        villaangelesDistances.put("Villa Angeles", 0);
        villaangelesDistances.put("Arellano", 650);
        villaangelesDistances.put("Bagumbayan", 600);
        villaangelesDistances.put("Balagtas", 1600);
        villaangelesDistances.put("Balut", 1100);
        villaangelesDistances.put("Bantan", 4600);
        villaangelesDistances.put("Bilolo", 1900);
        villaangelesDistances.put("Calungusan", 3300);
        villaangelesDistances.put("Camachile", 3900);
        villaangelesDistances.put("Daang Bago", 1400);
        villaangelesDistances.put("Daang Bilolo", 1300);
        villaangelesDistances.put("Daang Pare", 2600);
        villaangelesDistances.put("General Lim", 3900);
        villaangelesDistances.put("Kapunitan", 500);
        villaangelesDistances.put("Lati", 300);
        villaangelesDistances.put("Lusungan", 600);
        villaangelesDistances.put("Puting Buhangin", 4500);
        villaangelesDistances.put("Sabatan", 4200);
        villaangelesDistances.put("San Vicente", 2300);
        villaangelesDistances.put("Santa Elena", 4900);
        villaangelesDistances.put("Santo Domingo", 3400);
        villaangelesDistances.put("Wakas", 2700);
        villaangelesDistances.put("Wawa", 1200);
        distances.put("Villa Angeles", villaangelesDistances);

        Map<String, Integer> wakasDistances = new HashMap<>();
        wakasDistances.put("Wakas", 0);
        wakasDistances.put("Arellano", 3300);
        wakasDistances.put("Bagumbayan", 3300);
        wakasDistances.put("Balagtas", 4000);
        wakasDistances.put("Balut", 3900);
        wakasDistances.put("Bantan", 8600);
        wakasDistances.put("Bilolo", 1500);
        wakasDistances.put("Calungusan", 7300);
        wakasDistances.put("Camachile", 7900);
        wakasDistances.put("Daang Bago", 4100);
        wakasDistances.put("Daang Bilolo", 2600);
        wakasDistances.put("Daang Pare", 2300);
        wakasDistances.put("General Lim", 3300);
        wakasDistances.put("Kapunitan", 4000);
        wakasDistances.put("Lati", 3400);
        wakasDistances.put("Lusungan", 3700);
        wakasDistances.put("Puting Buhangin", 4300);
        wakasDistances.put("Sabatan", 2800);
        wakasDistances.put("San Vicente", 4700);
        wakasDistances.put("Santa Elena", 4600);
        wakasDistances.put("Santo Domingo", 5600);
        wakasDistances.put("Villa Angeles", 3300);
        wakasDistances.put("Wawa", 4000);
        distances.put("Wakas", wakasDistances);

        Map<String, Integer> wawaDistances = new HashMap<>();
        wawaDistances.put("Wawa", 0);
        wawaDistances.put("Arellano", 1300);
        wawaDistances.put("Bagumbayan", 1200);
        wawaDistances.put("Balagtas", 2200);
        wawaDistances.put("Balut", 1700);
        wawaDistances.put("Bantan", 5200);
        wawaDistances.put("Bilolo", 2500);
        wawaDistances.put("Calungusan", 3900);
        wawaDistances.put("Camachile", 4500);
        wawaDistances.put("Daang Bago", 140);
        wawaDistances.put("Daang Bilolo", 1900);
        wawaDistances.put("Daang Pare", 3600);
        wawaDistances.put("General Lim", 4600);
        wawaDistances.put("Kapunitan", 1300);
        wawaDistances.put("Lati", 1200);
        wawaDistances.put("Lusungan", 750);
        wawaDistances.put("Puting Buhangin", 5500);
        wawaDistances.put("Sabatan", 4800);
        wawaDistances.put("San Vicente", 2900);
        wawaDistances.put("Santa Elena", 5800);
        wawaDistances.put("Santo Domingo", 4000);
        wawaDistances.put("Villa Angeles", 1200);
        wawaDistances.put("Wakas", 3400);
        distances.put("Wawa", wawaDistances);
    }
    public static int getDistance(String fromBarangay, String toBarangay) {
        if (distances.containsKey(fromBarangay) && distances.get(fromBarangay).containsKey(toBarangay)) {
            return distances.get(fromBarangay).get(toBarangay);
        }
        return Integer.MAX_VALUE; // Return a high value if no direct distance is found
    }
}
